# Rustfmt Configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"

# Formatting style
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Auto"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments & Documentation
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Functions & Structs
fn_args_layout = "Tall"
fn_single_line = false
struct_lit_single_line = true
trailing_semicolon = true

# Control flow
match_block_trailing_comma = true
match_arm_blocks = true

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Misc
use_small_heuristics = "Default"
edition_style = "2021"
